Repository CapstoneProject-Notify/notify-server, pull requests merged in 2024-06, with the labels that each got.

#53 [feat] 카프카 역직렬화 추가
  build.gradle
  src/main/java/com/example/notifyserver/kafka/KafkaConsumer.java
  src/main/java/com/example/notifyserver/kafka/KafkaConsumerConfig.java
  src/main/java/com/example/notifyserver/kafka/NoticeListDeserializer.java
  src/main/java/com/example/notifyserver/notice/domain/Notice.java
Labels: feat

#54 [feat] 카프카 역직렬화 추가
  build.gradle
  src/main/java/com/example/notifyserver/kafka/KafkaConsumer.java
  src/main/java/com/example/notifyserver/kafka/KafkaConsumerConfig.java
  src/main/java/com/example/notifyserver/kafka/NoticeListDeserializer.java
  src/main/java/com/example/notifyserver/notice/domain/Notice.java
Labels: feat

#56 [fix] 공지사항에 카테고리 필드 추가
  src/main/java/com/example/notifyserver/common/domain/NoticeCategory.java
  src/main/java/com/example/notifyserver/notice/controller/NoticeController.java
  src/main/java/com/example/notifyserver/notice/domain/Notice.java
  src/main/java/com/example/notifyserver/notice/dto/NoticeResponse.java
  src/main/java/com/example/notifyserver/notice/repository/NoticeRepository.java
  src/main/java/com/example/notifyserver/notice/service/NoticeService.java
  src/main/java/com/example/notifyserver/notice/service/NoticeServiceImpl.java
Labels: fix

#57 [fix] 공지사항에 카테고리 필드 추가
  src/main/java/com/example/notifyserver/common/domain/NoticeCategory.java
  src/main/java/com/example/notifyserver/notice/controller/NoticeController.java
  src/main/java/com/example/notifyserver/notice/domain/Notice.java
  src/main/java/com/example/notifyserver/notice/dto/NoticeResponse.java
  src/main/java/com/example/notifyserver/notice/repository/NoticeRepository.java
  src/main/java/com/example/notifyserver/notice/service/NoticeService.java
  src/main/java/com/example/notifyserver/notice/service/NoticeServiceImpl.java
Labels: fix

#59 [refactor] Notify 서버로부터 이메일 서비스 분리
  build.gradle
  src/main/java/com/example/notifyserver/common/service/EmailService.java
  src/main/java/com/example/notifyserver/kafka/KafkaConsumer.java
  src/main/java/com/example/notifyserver/kafka/KafkaConsumerConfig.java
  src/main/java/com/example/notifyserver/kafka/NoticeListDeserializer.java
  src/main/java/com/example/notifyserver/user/service/UserService.java
Labels: refactor

#60 [refactor] Notify 서버로부터 이메일 서비스 분리
  build.gradle
  src/main/java/com/example/notifyserver/common/service/EmailService.java
  src/main/java/com/example/notifyserver/kafka/KafkaConsumer.java
  src/main/java/com/example/notifyserver/kafka/KafkaConsumerConfig.java
  src/main/java/com/example/notifyserver/kafka/NoticeListDeserializer.java
  src/main/java/com/example/notifyserver/user/service/UserService.java
Labels: refactor

#62 #61 [feat] 공지사항 조회 api 에 검색 로직 추가
  src/main/java/com/example/notifyserver/notice/controller/NoticeController.java
  src/main/java/com/example/notifyserver/notice/repository/NoticeRepository.java
  src/main/java/com/example/notifyserver/notice/service/NoticeService.java
  src/main/java/com/example/notifyserver/notice/service/NoticeServiceImpl.java
  src/main/resources/application.yml
Labels: feat
