Repository CapstoneProject-Notify/notify-server, pull requests merged in 2024-05, with the labels that each got.

#15 [bug] 회원 기능 및 스크랩 기능 CORS 적용
  src/main/java/com/example/notifyserver/scrap/controller/ScrapController.java
  src/main/java/com/example/notifyserver/user/controller/UserController.java
Labels: bug

#16 [hotfix] 회원 기능 및 스크랩 기능 CORS 적용
  src/main/java/com/example/notifyserver/common/config/WebConfig.java
  src/main/java/com/example/notifyserver/scrap/controller/ScrapController.java
  src/main/java/com/example/notifyserver/user/controller/UserController.java
Labels: bug

#19 #18 [feat] 회원탈퇴 기능 추가
  src/main/java/com/example/notifyserver/common/exception/enums/SuccessCode.java
  src/main/java/com/example/notifyserver/keyword/repository/KeywordRepository.java
  src/main/java/com/example/notifyserver/scrap/repository/ScrapRepository.java
  src/main/java/com/example/notifyserver/user/controller/UserController.java
  src/main/java/com/example/notifyserver/user/repository/UserRepository.java
  src/main/java/com/example/notifyserver/user/service/UserService.java
  src/main/resources/application.yml
Labels: feat

#22 #20 [feat] 공지사항 크롤링 기능 개발
  build.gradle
  src/main/java/com/example/notifyserver/aai_notice/domain/AaiNotice.java
  src/main/java/com/example/notifyserver/aai_notice/repository/AaiNoticeRepository.java
  src/main/java/com/example/notifyserver/bus_notice/domain/BusNotice.java
  src/main/java/com/example/notifyserver/bus_notice/repository/BusNoticeRepository.java
  src/main/java/com/example/notifyserver/com_notice/domain/ComNotice.java
  src/main/java/com/example/notifyserver/com_notice/repository/ComNoticeRepository.java
  src/main/java/com/example/notifyserver/common/constants/CrawlerConstants.java
  src/main/java/com/example/notifyserver/common/constants/NoticeConstants.java
  src/main/java/com/example/notifyserver/common/domain/NoticeType.java
  src/main/java/com/example/notifyserver/cos_notice/domain/CosNotice.java
  src/main/java/com/example/notifyserver/cos_notice/repository/CosNoticeRepository.java
  src/main/java/com/example/notifyserver/crawler/controller/CrawlerController.java
  src/main/java/com/example/notifyserver/crawler/dto/TitlesAndDates.java
  src/main/java/com/example/notifyserver/crawler/repository/CrawlerRepository.java
  src/main/java/com/example/notifyserver/crawler/service/CrawlerService.java
  src/main/java/com/example/notifyserver/crawler/service/CrawlerServiceImpl.java
  src/main/java/com/example/notifyserver/esm_notice/domain/EsmNotice.java
  src/main/java/com/example/notifyserver/esm_notice/repository/EsmNoticeRepository.java
  src/test/java/com/example/notifyserver/crawler/service/CrawlerServiceImplTest.java
  src/test/java/com/example/notifyserver/scrap/service/ScrapServiceImplTest.java
Labels: feat

#23 #20 [feat] 공지사항 크롤링 기능 개발
  build.gradle
  src/main/java/com/example/notifyserver/aai_notice/domain/AaiNotice.java
  src/main/java/com/example/notifyserver/aai_notice/repository/AaiNoticeRepository.java
  src/main/java/com/example/notifyserver/bus_notice/domain/BusNotice.java
  src/main/java/com/example/notifyserver/bus_notice/repository/BusNoticeRepository.java
  src/main/java/com/example/notifyserver/com_notice/domain/ComNotice.java
  src/main/java/com/example/notifyserver/com_notice/repository/ComNoticeRepository.java
  src/main/java/com/example/notifyserver/common/constants/CrawlerConstants.java
  src/main/java/com/example/notifyserver/common/constants/NoticeConstants.java
  src/main/java/com/example/notifyserver/common/domain/NoticeType.java
  src/main/java/com/example/notifyserver/cos_notice/domain/CosNotice.java
  src/main/java/com/example/notifyserver/cos_notice/repository/CosNoticeRepository.java
  src/main/java/com/example/notifyserver/crawler/controller/CrawlerController.java
  src/main/java/com/example/notifyserver/crawler/dto/TitlesAndDates.java
  src/main/java/com/example/notifyserver/crawler/repository/CrawlerRepository.java
  src/main/java/com/example/notifyserver/crawler/service/CrawlerService.java
  src/main/java/com/example/notifyserver/crawler/service/CrawlerServiceImpl.java
  src/main/java/com/example/notifyserver/esm_notice/domain/EsmNotice.java
  src/main/java/com/example/notifyserver/esm_notice/repository/EsmNoticeRepository.java
  src/test/java/com/example/notifyserver/crawler/service/CrawlerServiceImplTest.java
  src/test/java/com/example/notifyserver/scrap/service/ScrapServiceImplTest.java
Labels: feat

#25 #24 [bug] 스케줄링이 작동하지 않는 오류 해결
  src/main/java/com/example/notifyserver/NotifyServerApplication.java
  src/main/java/com/example/notifyserver/crawler/controller/CrawlerController.java
  src/main/java/com/example/notifyserver/crawler/service/CrawlerService.java
  src/main/java/com/example/notifyserver/crawler/service/CrawlerServiceImpl.java
Labels: bug

#26 #21 [feat] 이메일 기능 완성
  build.gradle
  src/main/java/com/example/notifyserver/common/domain/Notice.java
  src/main/java/com/example/notifyserver/common/repository/NoticeRepository.java
  src/main/java/com/example/notifyserver/common/service/EmailService.java
  src/main/java/com/example/notifyserver/keyword/domain/Keyword.java
  src/main/java/com/example/notifyserver/user/controller/UserController.java
  src/main/java/com/example/notifyserver/user/domain/User.java
  src/main/java/com/example/notifyserver/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/example/notifyserver/email/service/EmailServiceTest.java
  src/test/java/com/example/notifyserver/user/service/UserServiceTest.java
Labels: feat

#28 #27 [refactor] mailConfig 추가
  src/main/java/com/example/notifyserver/common/config/MailConfig.java
  src/main/resources/application.yml
Labels: refactor

#31 #29 [refactor] SecurityConfig session 추가
  build.gradle
  src/main/java/com/example/notifyserver/common/config/SecurityConfig.java
  src/main/java/com/example/notifyserver/user/controller/UserController.java
  src/main/java/com/example/notifyserver/user/service/UserService.java
Labels: refactor

#33 #32 [refactor] Mail Config 수정
  src/main/java/com/example/notifyserver/common/config/MailConfig.java
Labels: refactor

#35 #34 [refactor] security config
  src/main/java/com/example/notifyserver/common/config/SecurityConfig.java
  src/main/java/com/example/notifyserver/common/service/EmailService.java
  src/main/java/com/example/notifyserver/user/controller/UserController.java
  src/main/resources/application.yml
  src/test/java/com/example/notifyserver/email/service/EmailServiceTest.java
Labels: refactor

#38 #37 [refactor] 프로필 조회 기능 개발
  src/main/java/com/example/notifyserver/common/config/SecurityConfig.java
  src/main/java/com/example/notifyserver/common/dto/ApiResponse.java
  src/main/java/com/example/notifyserver/common/exception/enums/SuccessCode.java
  src/main/java/com/example/notifyserver/keyword/domain/Keyword.java
  src/main/java/com/example/notifyserver/keyword/repository/KeywordRepository.java
  src/main/java/com/example/notifyserver/user/controller/UserController.java
  src/main/java/com/example/notifyserver/user/dto/response/UserProfileResponse.java
  src/main/java/com/example/notifyserver/user/service/UserService.java
  src/main/resources/application.yml
Labels: feat

#40 #39 [feat] 키워드 추가 기능 개발
  src/main/java/com/example/notifyserver/common/exception/enums/SuccessCode.java
  src/main/java/com/example/notifyserver/keyword/controller/KeywordController.java
  src/main/java/com/example/notifyserver/keyword/domain/Keyword.java
  src/main/java/com/example/notifyserver/keyword/dto/request/KeywordAddRequest.java
  src/main/java/com/example/notifyserver/keyword/service/KeywordService.java
  src/main/java/com/example/notifyserver/user/controller/UserController.java
  src/main/resources/application.yml
Labels: feat

#44 #43 [feat] 공지사항 조회 기능 개발
  src/main/java/com/example/notifyserver/common/domain/NoticeType.java
  src/main/java/com/example/notifyserver/common/exception/enums/SuccessCode.java
  src/main/java/com/example/notifyserver/common/repository/NoticeRepository.java
  src/main/java/com/example/notifyserver/crawler/controller/CrawlerController.java
  src/main/java/com/example/notifyserver/crawler/repository/CrawlerRepository.java
  src/main/java/com/example/notifyserver/crawler/service/CrawlerService.java
  src/main/java/com/example/notifyserver/crawler/service/CrawlerServiceImpl.java
  src/main/java/com/example/notifyserver/notice/controller/NoticeController.java
  src/main/java/com/example/notifyserver/notice/domain/Notice.java
  src/main/java/com/example/notifyserver/notice/dto/NoticeResponse.java
  src/main/java/com/example/notifyserver/notice/repository/NoticeRepository.java
  src/main/java/com/example/notifyserver/notice/service/NoticeService.java
  src/main/java/com/example/notifyserver/notice/service/NoticeServiceImpl.java
  src/main/java/com/example/notifyserver/scrap/controller/ScrapController.java
  src/main/java/com/example/notifyserver/scrap/domain/Scrap.java
  src/main/java/com/example/notifyserver/scrap/repository/ScrapRepository.java
  src/main/java/com/example/notifyserver/scrap/service/ScrapService.java
  src/main/java/com/example/notifyserver/scrap/service/ScrapServiceImpl.java
  src/main/java/com/example/notifyserver/user/service/UserService.java
  src/test/java/com/example/notifyserver/crawler/service/CrawlerServiceImplTest.java
  src/test/java/com/example/notifyserver/scrap/service/ScrapServiceImplTest.java
Labels: feat

#45 #43 [feat] 공지사항 조회 기능 개발
  src/main/java/com/example/notifyserver/common/domain/NoticeType.java
  src/main/java/com/example/notifyserver/common/exception/enums/SuccessCode.java
  src/main/java/com/example/notifyserver/common/repository/NoticeRepository.java
  src/main/java/com/example/notifyserver/crawler/controller/CrawlerController.java
  src/main/java/com/example/notifyserver/crawler/repository/CrawlerRepository.java
  src/main/java/com/example/notifyserver/crawler/service/CrawlerService.java
  src/main/java/com/example/notifyserver/crawler/service/CrawlerServiceImpl.java
  src/main/java/com/example/notifyserver/notice/controller/NoticeController.java
  src/main/java/com/example/notifyserver/notice/domain/Notice.java
  src/main/java/com/example/notifyserver/notice/dto/NoticeResponse.java
  src/main/java/com/example/notifyserver/notice/repository/NoticeRepository.java
  src/main/java/com/example/notifyserver/notice/service/NoticeService.java
  src/main/java/com/example/notifyserver/notice/service/NoticeServiceImpl.java
  src/main/java/com/example/notifyserver/scrap/controller/ScrapController.java
  src/main/java/com/example/notifyserver/scrap/domain/Scrap.java
  src/main/java/com/example/notifyserver/scrap/repository/ScrapRepository.java
  src/main/java/com/example/notifyserver/scrap/service/ScrapService.java
  src/main/java/com/example/notifyserver/scrap/service/ScrapServiceImpl.java
  src/main/java/com/example/notifyserver/user/service/UserService.java
  src/test/java/com/example/notifyserver/crawler/service/CrawlerServiceImplTest.java
  src/test/java/com/example/notifyserver/scrap/service/ScrapServiceImplTest.java
Labels: feat

#48 [refactor] 크롤링 서버 분리 및 카프카 도입
  build.gradle
  src/main/java/com/example/notifyserver/crawler/controller/CrawlerController.java
  src/main/java/com/example/notifyserver/crawler/dto/TitlesAndDates.java
  src/main/java/com/example/notifyserver/crawler/repository/CrawlerRepository.java
  src/main/java/com/example/notifyserver/crawler/service/CrawlerService.java
  src/main/java/com/example/notifyserver/crawler/service/CrawlerServiceImpl.java
  src/main/java/com/example/notifyserver/kafka/KafkaConsumer.java
  src/test/java/com/example/notifyserver/crawler/service/CrawlerServiceImplTest.java
Labels: refactor

#49 [refactor] 크롤링 서버 분리 및 카프카 도입
  build.gradle
  src/main/java/com/example/notifyserver/crawler/controller/CrawlerController.java
  src/main/java/com/example/notifyserver/crawler/dto/TitlesAndDates.java
  src/main/java/com/example/notifyserver/crawler/repository/CrawlerRepository.java
  src/main/java/com/example/notifyserver/crawler/service/CrawlerService.java
  src/main/java/com/example/notifyserver/crawler/service/CrawlerServiceImpl.java
  src/main/java/com/example/notifyserver/kafka/KafkaConsumer.java
  src/test/java/com/example/notifyserver/crawler/service/CrawlerServiceImplTest.java
Labels: refactor

#51 [fix] 공지사항 조회 기능 로그 추가
  src/main/java/com/example/notifyserver/notice/controller/NoticeController.java
Labels: fix
